baseURL = "/"
languageCode = "sv-se"
title = "Fixora"
theme = "freelancer"

# Project specific params
[params]
# Hemsidans topp
  logoPath = "assets/logo-v1.svg"
  tagline = "Effektiva fastighetsprojekt för hållbar tillväxt"
  description = "Här ska det finnas en kort beskrivning som sammanfattar vad Fixora är och gör. Som en förlängning av taglinen."
  primaryAction = "Läs mer"
  secondaryAction = "Förfrågan"

# Kontakt
  contactHeader = "Kontakt"
  contactSubHeader = "Använd formuläret nedan för att skicka en förfrågan, eller ring eller mejla för mer information."
  formLabelName = "Namn"
  formLabelEmail = "E-post"
  formLabelMessage = "Meddelande"
  formAction = "Skicka"
  location = "Landskrona"
  contactEmail = "info@fixora.se"
  contactPhone = "070 111 11 11"
  linkedIn = "linkedin.com/in/jennyhedelin"

# Footer
  author = "Fixora"
  year = "2020"

# Navigering
[menu]
[[menu.main]]
    identifier = "hem"
    name = "Hem"
    url = "/"
    weight = 100

  [[menu.main]]
    identifier = "intro"
    name = "Intro"
    url = "#intro"
    weight = 110

  [[menu.main]]
    identifier = "tjanster"
    name = "Tjänster"
    url = "#tjanster"
    weight = 120
  
  [[menu.main]]
    identifier = "om"
    name = "Om mig"
    url = "#om"
    weight = 130

  [[menu.main]]
    identifier = "kontakt"
    name = "Kontakt"
    url = "#kontakt"
    weight = 140
