baseURL = "/"
languageCode = "sv-se"
title = "Fixora"
theme = "freelancer"

# Project specific params
[params]
  description = "Här ska det finnas en kort beskrivning som sammanfattar vad Fixora är och gör. Som en förlängning av taglinen."
  author = "The Author"
  tagline = "Effektiva fastighetsprojekt för hållbar tillväxt"
  logoPath = "assets/logo-v1.svg"

# Main menu
[menu]
  [[menu.main]]
    identifier = "intro"
    name = "Intro"
    url = "#intro"
    weight = 100

  [[menu.main]]
    identifier = "tjanster"
    name = "Tjänster"
    url = "#tjanster"
    weight = 110
  
  [[menu.main]]
    identifier = "om"
    name = "Om mig"
    url = "#om"
    weight = 120

  [[menu.main]]
    identifier = "kontakt"
    name = "Kontakt"
    url = "#kontakt"
    weight = 130
